### ISSUE TITLE
Rational Class

### ISSUE THREAD

**Issue by thisisagithubaccounta** [blackmathx/scientific-java-library#4]
I'm thinking of doing a bit of work on the Rational class and I think there's a couple of discussions to be had around it.

- Should all rationals be simplified automatically?
- What would be the difference between the abs function and the toDouble function?
- I think greatestCommonDivisor and lowestCommonMultiple should be in there own class, there not specifically to do with Rationals?

What do you think?

**Comment by blackmathx** [comment]
1. I do not think all rationals should be simplified, in case rationals represent a counted number of objects, or often in statistics a ratio must not be simplified. A reduce() function will provide simplifying.

2. If the rational number is negative, abs() function returns -1*rational, otherwise its positive and abs() returns the rational number. The toDouble() function returns the decimal.

3. A class called IntegerFunctions can contain leastCommonMultiple, greatestCommonDiviser, and uniqueFactorization that returns an array.  If you would like to write this class, then it should also contain  functions such as boolean prime(), and int modular(int a, int modB).

**Comment by blackmathx** [comment]
I moved 3 into a new Issue.

**Comment by blackmathx** [comment]
4. Rational.java could use a method to split a string like "11/52" into a rational number.

**Comment by thisisagithubaccounta** [comment]
I like that idea of splitting a string, ill add that in.
